// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnX-p5zv6u1-OU3hYJxBMQGwek2Eor_dE',
    appId: '1:141353480398:web:cad55482bc29f0c681209f',
    messagingSenderId: '141353480398',
    projectId: 'cakeshop-afc3f',
    authDomain: 'cakeshop-afc3f.firebaseapp.com',
    storageBucket: 'cakeshop-afc3f.firebasestorage.app',
    measurementId: 'G-VX4RMTS08X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcaetqjVCwETGECGmLMpNQKR2033UR4gA',
    appId: '1:141353480398:android:92616c9e6fe50ef081209f',
    messagingSenderId: '141353480398',
    projectId: 'cakeshop-afc3f',
    storageBucket: 'cakeshop-afc3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB4CzT0IgawWfswNFb400D7klx8kny6-E',
    appId: '1:141353480398:ios:5f30eeba163201c581209f',
    messagingSenderId: '141353480398',
    projectId: 'cakeshop-afc3f',
    storageBucket: 'cakeshop-afc3f.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectSanbercode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB4CzT0IgawWfswNFb400D7klx8kny6-E',
    appId: '1:141353480398:ios:5f30eeba163201c581209f',
    messagingSenderId: '141353480398',
    projectId: 'cakeshop-afc3f',
    storageBucket: 'cakeshop-afc3f.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectSanbercode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnX-p5zv6u1-OU3hYJxBMQGwek2Eor_dE',
    appId: '1:141353480398:web:3c043a2c2d3df26181209f',
    messagingSenderId: '141353480398',
    projectId: 'cakeshop-afc3f',
    authDomain: 'cakeshop-afc3f.firebaseapp.com',
    storageBucket: 'cakeshop-afc3f.firebasestorage.app',
    measurementId: 'G-10KW9QY920',
  );
}
